# FIFA
41692356A - Fons Riera, Pere

<a href = "https://github.com/EnergyWoxt/Pr-ctica-Machine-Learning-IA">Repositori de Referènecia</a>

Aquesta és una pràctica d'intel·ligència artificial que té com objectiu generar un model de regressió per preveure el preu d'un jugador donades les seves característiques. En aquest cas ens decantam per dur a terme una regressió lineal.

Anem a dur a terme totes les impotacions que haurem d'utilitzar per dur a terme aquest treball: pandas per poder tractar les dades importades i sklearn per separar el set d'entrenament del de prova, dur a terme la regressió lineal i analitzar el resultat de la regressió.

In [29]:
import os

from sklearn.model_selection import train_test_split
from sklearn import linear_model
from sklearn.metrics import r2_score

import pandas as pandas

Configuram el pandas perquè ens mostri totes les columnes del dataframe i tenir visibilitat per saber què representen cada una d'elles.

In [30]:
pandas.set_option('display.max_columns', None)

Llegim la informació del fitxer per carregar el dataframe a memòria que necessitarem per fer l'estudi i mostram la capçalera del dataframe:

In [31]:
df = pandas.read_csv(os.path.join("in", "fifa.csv"))
df.head()

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,Club Logo,Value,Wage,Special,Preferred Foot,International Reputation,Weak Foot,Skill Moves,Work Rate,Body Type,Real Face,Position,Jersey Number,Joined,Loaned From,Contract Valid Until,Height,Weight,LS,ST,RS,LW,LF,CF,RF,RW,LAM,CAM,RAM,LM,LCM,CM,RCM,RM,LWB,LDM,CDM,RDM,RWB,LB,LCB,CB,RCB,RB,Crossing,Finishing,HeadingAccuracy,ShortPassing,Volleys,Dribbling,Curve,FKAccuracy,LongPassing,BallControl,Acceleration,SprintSpeed,Agility,Reactions,Balance,ShotPower,Jumping,Stamina,Strength,LongShots,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/158023.png,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,https://cdn.sofifa.org/teams/2/light/241.png,€110.5M,€565K,2202,Left,5.0,4.0,4.0,Medium/ Medium,Messi,Yes,RF,10.0,"Jul 1, 2004",NaN,2021,5'7,159lbs,88+2,88+2,88+2,92+2,93+2,93+2,93+2,92+2,93+2,93+2,93+2,91+2,84+2,84+2,84+2,91+2,64+2,61+2,61+2,61+2,64+2,59+2,47+2,47+2,47+2,59+2,84.0,95.0,70.0,90.0,86.0,97.0,93.0,94.0,87.0,96.0,91.0,86.0,91.0,95.0,95.0,85.0,68.0,72.0,59.0,94.0,48.0,22.0,94.0,94.0,75.0,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
1,1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/20801.png,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Juventus,https://cdn.sofifa.org/teams/2/light/45.png,€77M,€405K,2228,Right,5.0,4.0,5.0,High/ Low,C. Ronaldo,Yes,ST,7.0,"Jul 10, 2018",NaN,2022,6'2,183lbs,91+3,91+3,91+3,89+3,90+3,90+3,90+3,89+3,88+3,88+3,88+3,88+3,81+3,81+3,81+3,88+3,65+3,61+3,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3,84.0,94.0,89.0,81.0,87.0,88.0,81.0,76.0,77.0,94.0,89.0,91.0,87.0,96.0,70.0,95.0,95.0,88.0,79.0,93.0,63.0,29.0,95.0,82.0,85.0,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
2,2,190871,Neymar Jr,26,https://cdn.sofifa.org/players/4/19/190871.png,Brazil,https://cdn.sofifa.org/flags/54.png,92,93,Paris Saint-Germain,https://cdn.sofifa.org/teams/2/light/73.png,€118.5M,€290K,2143,Right,5.0,5.0,5.0,High/ Medium,Neymar,Yes,LW,10.0,"Aug 3, 2017",NaN,2022,5'9,150lbs,84+3,84+3,84+3,89+3,89+3,89+3,89+3,89+3,89+3,89+3,89+3,88+3,81+3,81+3,81+3,88+3,65+3,60+3,60+3,60+3,65+3,60+3,47+3,47+3,47+3,60+3,79.0,87.0,62.0,84.0,84.0,96.0,88.0,87.0,78.0,95.0,94.0,90.0,96.0,94.0,84.0,80.0,61.0,81.0,49.0,82.0,56.0,36.0,89.0,87.0,81.0,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M
3,3,193080,De Gea,27,https://cdn.sofifa.org/players/4/19/193080.png,Spain,https://cdn.sofifa.org/flags/45.png,91,93,Manchester United,https://cdn.sofifa.org/teams/2/light/11.png,€72M,€260K,1471,Right,4.0,3.0,1.0,Medium/ Medium,Lean,Yes,GK,1.0,"Jul 1, 2011",NaN,2020,6'4,168lbs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.0,13.0,21.0,50.0,13.0,18.0,21.0,19.0,51.0,42.0,57.0,58.0,60.0,90.0,43.0,31.0,67.0,43.0,64.0,12.0,38.0,30.0,12.0,68.0,40.0,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M
4,4,192985,K. De Bruyne,27,https://cdn.sofifa.org/players/4/19/192985.png,Belgium,https://cdn.sofifa.org/flags/7.png,91,92,Manchester City,https://cdn.sofifa.org/teams/2/light/10.png,€102M,€355K,2281,Right,4.0,5.0,4.0,High/ High,Normal,Yes,RCM,7.0,"Aug 30, 2015",NaN,2023,5'11,154lbs,82+3,82+3,82+3,87+3,87+3,87+3,87+3,87+3,88+3,88+3,88+3,88+3,87+3,87+3,87+3,88+3,77+3,77+3,77+3,77+3,77+3,73+3,66+3,66+3,66+3,73+3,93.0,82.0,55.0,92.0,82.0,86.0,85.0,83.0,91.0,91.0,78.0,76.0,79.0,91.0,77.0,91.0,63.0,90.0,75.0,91.0,76.0,61.0,87.0,94.0,79.0,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M

# Tractament de les dades
És essencial analitzar i convertir les dades per poder fer una bona regressió lineal.

Després de analitzar el resultat es pot concluir que hi ha característiques que no ens donen cap informació significativa de manera intuitiva respecte del valor que volem preveure. Eliminar-les pot suposar eliminar renou que empitjora la qualitat de la nostra predicció. Anem a eliminar-les seguint un raonament per a cada una:
1. "Unnamed: 0": indica un ordre intern dels jugadors dins el dataframe, no dóna informació que pugui justificar un cost o un altre.
2. "ID": és l'identificador intern del jugador. Clarament té un  ús funcional per a l'accés a les dades i no ens serveix per fer inferències del valor del jugador.
3. "Name": el nom del jugador, que és una cadena de caràcters, no afecta al cost que pugui tenir en funció del seu contingut: més aviat és la reputació internacional associada a aquest nom que pot generar un impacte en el preu. A més a més s'hauria de plantejar una funció discreta de mapeig del nom a un valor numèric, que per la majoria de jugadors seria únic.
4. "Photo": és una url, una cadena de caràcters que serveix per accedir a la fotografia del jugador. No ens aporta informació rellevant respecte del preu. De fet, la foto a la que direcciona no serà usada perquè les característiques físiques d'aspecte que té un jugador no són d'ajuda per determinar el seu preu en una disciplina esportiva.
5. "Flag": és una url, una cadena de caràcters que serveix per accedir a la fotografia de la bandera del país del jugador. A més a més no té sentit que la bandera de la nacionalitat ajudi a determinar el preu del jugador.
6. "Club Logo": és una url, una cadena de caràcters que serveix per accedir a la fotografia de la bandera del club del jugador. Molt similar a casos anteriors, no té rellevància per inferir el valor dins el nostre problema.
7. "Body Type": és el tipus de cos que rebrà el jugador dins el joc en forma de model 3D. El seu significat no va més enllà de la lògica del joc.
8. "Real Face": és la cara que rebrà el jugador dins el joc en forma de model 3D. S'aplica la mateixa lògica que en el cas anterior.
9. "Jersey Number": és el nombre que ha de tenir l'uniforme del jugador. Més enllà de supersticions i especulacions extranyes respecte del nombre no afecta al valor del jugador.
10. "Loaned from": representa de quin club s'ha manllevat el jugador. No té lògica que afecti en si al preu que té el jugador, s'hagi manllevat del Barça com del Betis el seu preu no es veu afectat.
11. "Contract valid until": representa la data d'expiració del contracte vigent. El fet que acabi més prest o més tard per una qüestió de lògica no afecta al valor del jugador. 
12. "Special": determina si els jugadors tenen cartes commemoratives. No té sentit que si en tenen o no el preu es vegi afectat. 
13. "Joined": el moment en què es varen unir a la plantilla de jugadors. No afecta de manera directa al seu rendiment ni preu.
14. "Nationallity": no té lògica que allà on va nèixer un jugador pugui determinar el preu que té. 
15. "Preferred Foot": a efectes pràctics és igual si un jugador prefereix el peu dret o esquerra per determinar el seu preu.

In [32]:
df.drop("Unnamed: 0", axis=1, inplace=True)
df.drop("ID", axis=1, inplace=True)
df.drop("Name", axis=1, inplace=True)
df.drop("Photo", axis=1, inplace=True)
df.drop("Flag", axis=1, inplace=True)
df.drop("Club Logo", axis=1, inplace=True)
df.drop("Joined", axis=1, inplace=True)
df.drop("Body Type", axis=1, inplace=True)
df.drop("Real Face", axis=1, inplace=True)
df.drop("Jersey Number", axis=1, inplace=True)
df.drop("Loaned From", axis=1, inplace=True)
df.drop("Contract Valid Until", axis=1, inplace=True)
df.drop("Special", axis=1, inplace=True)
df.drop("Nationality", axis=1, inplace=True)
df.drop("Preferred Foot", axis=1, inplace=True)

Anem a veure com ha quedat el nostre dataframe després de les eliminacions:

In [33]:
df.head()

,Age,Overall,Potential,Club,Value,Wage,International Reputation,Weak Foot,Skill Moves,Work Rate,Position,Height,Weight,LS,ST,RS,LW,LF,CF,RF,RW,LAM,CAM,RAM,LM,LCM,CM,RCM,RM,LWB,LDM,CDM,RDM,RWB,LB,LCB,CB,RCB,RB,Crossing,Finishing,HeadingAccuracy,ShortPassing,Volleys,Dribbling,Curve,FKAccuracy,LongPassing,BallControl,Acceleration,SprintSpeed,Agility,Reactions,Balance,ShotPower,Jumping,Stamina,Strength,LongShots,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,31,94,94,FC Barcelona,€110.5M,€565K,5.0,4.0,4.0,Medium/ Medium,RF,5'7,159lbs,88+2,88+2,88+2,92+2,93+2,93+2,93+2,92+2,93+2,93+2,93+2,91+2,84+2,84+2,84+2,91+2,64+2,61+2,61+2,61+2,64+2,59+2,47+2,47+2,47+2,59+2,84.0,95.0,70.0,90.0,86.0,97.0,93.0,94.0,87.0,96.0,91.0,86.0,91.0,95.0,95.0,85.0,68.0,72.0,59.0,94.0,48.0,22.0,94.0,94.0,75.0,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
1,33,94,94,Juventus,€77M,€405K,5.0,4.0,5.0,High/ Low,ST,6'2,183lbs,91+3,91+3,91+3,89+3,90+3,90+3,90+3,89+3,88+3,88+3,88+3,88+3,81+3,81+3,81+3,88+3,65+3,61+3,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3,84.0,94.0,89.0,81.0,87.0,88.0,81.0,76.0,77.0,94.0,89.0,91.0,87.0,96.0,70.0,95.0,95.0,88.0,79.0,93.0,63.0,29.0,95.0,82.0,85.0,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
2,26,92,93,Paris Saint-Germain,€118.5M,€290K,5.0,5.0,5.0,High/ Medium,LW,5'9,150lbs,84+3,84+3,84+3,89+3,89+3,89+3,89+3,89+3,89+3,89+3,89+3,88+3,81+3,81+3,81+3,88+3,65+3,60+3,60+3,60+3,65+3,60+3,47+3,47+3,47+3,60+3,79.0,87.0,62.0,84.0,84.0,96.0,88.0,87.0,78.0,95.0,94.0,90.0,96.0,94.0,84.0,80.0,61.0,81.0,49.0,82.0,56.0,36.0,89.0,87.0,81.0,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M
3,27,91,93,Manchester United,€72M,€260K,4.0,3.0,1.0,Medium/ Medium,GK,6'4,168lbs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.0,13.0,21.0,50.0,13.0,18.0,21.0,19.0,51.0,42.0,57.0,58.0,60.0,90.0,43.0,31.0,67.0,43.0,64.0,12.0,38.0,30.0,12.0,68.0,40.0,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M
4,27,91,92,Manchester City,€102M,€355K,4.0,5.0,4.0,High/ High,RCM,5'11,154lbs,82+3,82+3,82+3,87+3,87+3,87+3,87+3,87+3,88+3,88+3,88+3,88+3,87+3,87+3,87+3,88+3,77+3,77+3,77+3,77+3,77+3,73+3,66+3,66+3,66+3,73+3,93.0,82.0,55.0,92.0,82.0,86.0,85.0,83.0,91.0,91.0,78.0,76.0,79.0,91.0,77.0,91.0,63.0,90.0,75.0,91.0,76.0,61.0,87.0,94.0,79.0,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M

## Tractament de camps NaN

Anem a tractar tots aquells camps que no tenguin un valor assignat plantejant les següents estratègies:

1. Analitzar on trobam NaNs.
2. Per a cada un dels llocs on els trobam anem a aplicar una estratègia concreta per desfer-nos d'ells.

Analitzem els NaNs.
Primer a les files on apareixen:

In [34]:
df[df.isna().any(axis = 1)]

,Age,Overall,Potential,Club,Value,Wage,International Reputation,Weak Foot,Skill Moves,Work Rate,Position,Height,Weight,LS,ST,RS,LW,LF,CF,RF,RW,LAM,CAM,RAM,LM,LCM,CM,RCM,RM,LWB,LDM,CDM,RDM,RWB,LB,LCB,CB,RCB,RB,Crossing,Finishing,HeadingAccuracy,ShortPassing,Volleys,Dribbling,Curve,FKAccuracy,LongPassing,BallControl,Acceleration,SprintSpeed,Agility,Reactions,Balance,ShotPower,Jumping,Stamina,Strength,LongShots,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
3,27,91,93,Manchester United,€72M,€260K,4.0,3.0,1.0,Medium/ Medium,GK,6'4,168lbs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.0,13.0,21.0,50.0,13.0,18.0,21.0,19.0,51.0,42.0,57.0,58.0,60.0,90.0,43.0,31.0,67.0,43.0,64.0,12.0,38.0,30.0,12.0,68.0,40.0,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M
9,25,90,93,Atlético Madrid,€68M,€94K,3.0,3.0,1.0,Medium/ Medium,GK,6'2,192lbs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,11.0,15.0,29.0,13.0,12.0,13.0,14.0,26.0,16.0,43.0,60.0,67.0,86.0,49.0,22.0,76.0,41.0,78.0,12.0,34.0,19.0,11.0,70.0,11.0,70.0,27.0,12.0,18.0,86.0,92.0,78.0,88.0,89.0,€144.5M
18,26,89,92,FC Barcelona,€58M,€240K,3.0,4.0,1.0,Medium/ Medium,GK,6'2,187lbs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.0,14.0,11.0,36.0,14.0,17.0,18.0,12.0,42.0,18.0,38.0,50.0,37.0,85.0,43.0,22.0,79.0,35.0,79.0,10.0,43.0,22.0,11.0,69.0,25.0,69.0,25.0,13.0,10.0,87.0,85.0,88.0,85.0,90.0,€123.3M
19,26,89,90,Real Madrid,€53.5M,€240K,4.0,2.0,1.0,Medium/ Medium,GK,6'6,212lbs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.0,14.0,13.0,33.0,12.0,13.0,19.0,20.0,35.0,23.0,46.0,52.0,61.0,84.0,45.0,36.0,68.0,38.0,70.0,17.0,23.0,15.0,13.0,44.0,27.0,66.0,20.0,18.0,16.0,85.0,91.0,72.0,86.0,88.0,€113.7M
22,32,89,89,FC Bayern München,€38M,€130K,5.0,4.0,1.0,Medium/ Medium,GK,6'4,203lbs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.0,13.0,25.0,55.0,11.0,30.0,14.0,11.0,59.0,48.0,54.0,60.0,51.0,84.0,35.0,25.0,77.0,43.0,80.0,16.0,29.0,30.0,12.0,70.0,47.0,70.0,17.0,10.0,11.0,90.0,86.0,91.0,87.0,87.0,€62.7M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18178,18,48,65,Dalkurd FF,€50K,€1K,1.0,2.0,1.0,Medium/ Medium,GK,6'0,176lbs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,7.0,11.0,22.0,6.0,8.0,10.0,8.0,20.0,12.0,24.0,28.0,33.0,40.0,29.0,15.0,48.0,20.0,38.0,6.0,20.0,10.0,7.0,18.0,12.0,28.0,16.0,11.0,10.0,47.0,46.0,50.0,45.0,51.0,€94K
18180,22,48,58,St. Johnstone FC,€40K,€1K,1.0,2.0,1.0,Medium/ Medium,GK,6'1,172lbs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.0,15.0,15.0,26.0,14.0,13.0,12.0,19.0,19.0,25.0,40.0,42.0,45.0,47.0,52.0,25.0,55.0,33.0,58.0,20.0,20.0,29.0,13.0,20.0,29.0,28.0,12.0,15.0,16.0,45.0,49.0,50.0,50.0,45.0,€78K
18183,44,48,48,Cambridge United,€0,€1K,1.0,2.0,1.0,Medium/ Medium,GK,6'2,190lbs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.0,12.0,12.0,18.0,11.0,11.0,12.0,13.0,13.0,16.0,15.0,17.0,31.0,48.0,31.0,23.0,45.0,22.0,44.0,12.0,24.0,15.0,10.0,11.0,22.0,56.0,15.0,15.0,13.0,45.0,48.0,44.0,49.0,46.0,NaN
18194,18,47,65,Lecce,€50K,€1K,1.0,3.0,1.0,Medium/ Medium,GK,6'3,187lbs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,6.0,10.0,25.0,6.0,12.0,13.0,10.0,20.0,17.0,20.0,14.0,39.0,37.0,22.0,22.0,33.0,15.0,59.0,5.0,17.0,5.0,3.0,28.0,16.0,23.0,6.0,10.0,11.0,52.0,52.0,52.0,40.0,44.0,€109K
18198,18,47,70,Burton Albion,€60K,€1K,1.0,2.0,1.0,Medium/ Medium,GK,5'11,154lbs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.0,8.0,14.0,19.0,8.0,10.0,13.0,10.0,21.0,11.0,18.0,24.0,22.0,36.0,47.0,26.0,56.0,20.0,38.0,5.0,25.0,6.0,5.0,37.0,14.0,34.0,15.0,11.0,13.0,46.0,52.0,58.0,42.0,48.0,€165K

Llavors a les columnes on n'apareixen:

In [35]:
df.columns[df.isna().any()]

Index(['Club', 'International Reputation', 'Weak Foot', 'Skill Moves',
       'Work Rate', 'Position', 'Height', 'Weight', 'LS', 'ST', 'RS', 'LW',
       'LF', 'CF', 'RF', 'RW', 'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM', 'RCM',
       'RM', 'LWB', 'LDM', 'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB', 'RCB', 'RB',
       'Crossing', 'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys',
       'Dribbling', 'Curve', 'FKAccuracy', 'LongPassing', 'BallControl',
       'Acceleration', 'SprintSpeed', 'Agility', 'Reactions', 'Balance',
       'ShotPower', 'Jumping', 'Stamina', 'Strength', 'LongShots',
       'Aggression', 'Interceptions', 'Positioning', 'Vision', 'Penalties',
       'Composure', 'Marking', 'StandingTackle', 'SlidingTackle', 'GKDiving',
       'GKHandling', 'GKKicking', 'GKPositioning', 'GKReflexes',
       'Release Clause'],
      dtype='object')

Podem apreciar que hi ha un grup ben diferenciat que són porters (GK), aquests tenen una gran quantitat de camps d'estadístiques sense valor i a més tenen estadístiques de porter molt diferents als jugadors que juguen a qualsevol posició, cosa que pot generar renou en les prediccions. Per conveniència els eliminarem (ho podem fer perquè són una fracció petita dels jugadors):

In [36]:
print(str(100 * len(df[df.Position == "GK"].index)/len(df.index)) + "% del dataframe eliminat")

df = df[df.Position != "GK"]
df[df.isna().any(axis=1)]

11.122095897182403% del dataframe eliminat

,Age,Overall,Potential,Club,Value,Wage,International Reputation,Weak Foot,Skill Moves,Work Rate,Position,Height,Weight,LS,ST,RS,LW,LF,CF,RF,RW,LAM,CAM,RAM,LM,LCM,CM,RCM,RM,LWB,LDM,CDM,RDM,RWB,LB,LCB,CB,RCB,RB,Crossing,Finishing,HeadingAccuracy,ShortPassing,Volleys,Dribbling,Curve,FKAccuracy,LongPassing,BallControl,Acceleration,SprintSpeed,Agility,Reactions,Balance,ShotPower,Jumping,Stamina,Strength,LongShots,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
28,26,88,89,FC Bayern München,€69.5M,€315K,4.0,3.0,4.0,Medium/ Medium,LAM,5'11,172lbs,80+3,80+3,80+3,84+3,83+3,83+3,83+3,84+3,85+3,85+3,85+3,83+3,81+3,81+3,81+3,83+3,69+3,68+3,68+3,68+3,69+3,65+3,58+3,58+3,58+3,65+3,90.0,83.0,62.0,89.0,90.0,85.0,89.0,86.0,83.0,90.0,73.0,67.0,83.0,85.0,76.0,86.0,54.0,70.0,68.0,92.0,64.0,55.0,80.0,89.0,81.0,87.0,52.0,41.0,44.0,15.0,15.0,15.0,5.0,14.0,NaN
38,30,88,88,Milan,€57M,€245K,4.0,4.0,3.0,High/ Medium,LS,6'1,196lbs,85+3,85+3,85+3,81+3,83+3,83+3,83+3,81+3,80+3,80+3,80+3,78+3,71+3,71+3,71+3,78+3,55+3,53+3,53+3,53+3,55+3,51+3,48+3,48+3,48+3,51+3,68.0,92.0,80.0,75.0,90.0,84.0,74.0,62.0,59.0,85.0,73.0,73.0,75.0,86.0,69.0,86.0,79.0,70.0,85.0,80.0,50.0,20.0,92.0,74.0,70.0,86.0,35.0,22.0,18.0,5.0,12.0,7.0,5.0,10.0,NaN
91,29,85,85,Guangzhou Evergrande Taobao FC,€37M,€235K,3.0,3.0,3.0,High/ High,LDM,6'0,157lbs,81+3,81+3,81+3,79+3,81+3,81+3,81+3,79+3,81+3,81+3,81+3,79+3,82+3,82+3,82+3,79+3,78+3,81+3,81+3,81+3,78+3,78+3,80+3,80+3,80+3,78+3,64.0,81.0,85.0,84.0,75.0,82.0,66.0,72.0,80.0,84.0,73.0,73.0,69.0,84.0,66.0,83.0,90.0,92.0,81.0,80.0,81.0,81.0,84.0,78.0,71.0,80.0,75.0,81.0,73.0,16.0,16.0,11.0,6.0,8.0,NaN
166,24,83,90,Guangzhou Evergrande Taobao FC,€36.5M,€18K,2.0,4.0,4.0,High/ Medium,CAM,6'3,176lbs,80+2,80+2,80+2,81+2,81+2,81+2,81+2,81+2,81+2,81+2,81+2,80+2,79+2,79+2,79+2,80+2,69+2,69+2,69+2,69+2,69+2,67+2,64+2,64+2,64+2,67+2,78.0,80.0,77.0,81.0,76.0,82.0,86.0,87.0,79.0,84.0,77.0,76.0,76.0,79.0,65.0,84.0,58.0,76.0,72.0,88.0,67.0,58.0,86.0,81.0,71.0,74.0,55.0,62.0,42.0,13.0,11.0,13.0,12.0,10.0,NaN
176,24,83,89,Chelsea,€35M,€165K,3.0,4.0,4.0,High/ High,LCM,5'9,172lbs,71+3,71+3,71+3,79+3,78+3,78+3,78+3,79+3,81+3,81+3,81+3,80+3,82+3,82+3,82+3,80+3,76+3,78+3,78+3,78+3,76+3,74+3,69+3,69+3,69+3,74+3,73.0,62.0,42.0,87.0,76.0,88.0,78.0,68.0,82.0,89.0,84.0,74.0,81.0,70.0,85.0,79.0,63.0,82.0,65.0,75.0,77.0,78.0,69.0,88.0,59.0,72.0,69.0,75.0,63.0,9.0,5.0,6.0,7.0,7.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17978,21,51,57,Hamilton Academical FC,€50K,€3K,1.0,2.0,2.0,Medium/ Medium,ST,5'11,165lbs,49+2,49+2,49+2,49+2,49+2,49+2,49+2,49+2,47+2,47+2,47+2,47+2,40+2,40+2,40+2,47+2,34+2,31+2,31+2,31+2,34+2,33+2,30+2,30+2,30+2,33+2,34.0,53.0,44.0,38.0,40.0,50.0,39.0,26.0,33.0,48.0,64.0,74.0,56.0,49.0,65.0,42.0,62.0,48.0,60.0,43.0,35.0,16.0,47.0,45.0,62.0,49.0,14.0,13.0,13.0,12.0,13.0,16.0,9.0,14.0,NaN
17979,21,51,60,Guizhou Hengfeng FC,€60K,€2K,1.0,2.0,2.0,Medium/ Medium,CM,6'0,172lbs,49+2,49+2,49+2,50+2,50+2,50+2,50+2,50+2,50+2,50+2,50+2,51+2,50+2,50+2,50+2,51+2,50+2,50+2,50+2,50+2,50+2,50+2,49+2,49+2,49+2,50+2,36.0,30.0,48.0,57.0,32.0,45.0,37.0,38.0,55.0,50.0,71.0,76.0,75.0,55.0,58.0,55.0,60.0,62.0,61.0,33.0,58.0,41.0,53.0,47.0,36.0,43.0,47.0,41.0,46.0,12.0,12.0,10.0,13.0,9.0,NaN
18026,21,50,59,Guizhou Hengfeng FC,€50K,€2K,1.0,2.0,2.0,Medium/ Medium,LM,5'10,143lbs,44+2,44+2,44+2,47+2,46+2,46+2,46+2,47+2,48+2,48+2,48+2,49+2,48+2,48+2,48+2,49+2,50+2,50+2,50+2,50+2,50+2,51+2,50+2,50+2,50+2,51+2,41.0,28.0,50.0,54.0,26.0,50.0,39.0,40.0,55.0,46.0,61.0,77.0,76.0,50.0,74.0,47.0,63.0,50.0,52.0,29.0,56.0,50.0,37.0,49.0,42.0,38.0,46.0,48.0,51.0,15.0,8.0,10.0,13.0,7.0,NaN
18031,20,50,61,Stabæk Fotball,€40K,€2K,1.0,3.0,2.0,Medium/ Medium,RB,5'7,143lbs,37+2,37+2,37+2,42+2,40+2,40+2,40+2,42+2,39+2,39+2,39+2,43+2,38+2,38+2,38+2,43+2,48+2,43+2,43+2,43+2,48+2,48+2,45+2,45+2,45+2,48+2,46.0,29.0,35.0,32.0,26.0,52.0,32.0,28.0,22.0,34.0,60.0,58.0,57.0,47.0,85.0,29.0,64.0,64.0,32.0,29.0,54.0,54.0,43.0,38.0,38.0,32.0,51.0,48.0,48.0,11.0,7.0,9.0,10.0,6.0,NaN
18056,19,50,65,Ascoli,€60K,€3K,1.0,3.0,2.0,Medium/ Medium,CM,5'10,143lbs,44+2,44+2,44+2,47+2,45+2,45+2,45+2,47+2,47+2,47+2,47+2,49+2,48+2,48+2,48+2,49+2,52+2,51+2,51+2,51+2,52+2,52+2,51+2,51+2,51+2,52+2,50.0,30.0,50.0,54.0,40.0,50.0,40.0,40.0,50.0,50.0,62.0,63.0,60.0,52.0,65.0,50.0,64.0,52.0,54.0,40.0,60.0,49.0,26.0,49.0,40.0,42.0,41.0,54.0,55.0,8.0,11.0,13.0,14.0,14.0,NaN

Anem a veure quines  columnes ens queden encara amb NaN:

In [37]:
df.columns[df.isna().any()]

Index(['Club', 'International Reputation', 'Weak Foot', 'Skill Moves',
       'Work Rate', 'Position', 'Height', 'Weight', 'LS', 'ST', 'RS', 'LW',
       'LF', 'CF', 'RF', 'RW', 'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM', 'RCM',
       'RM', 'LWB', 'LDM', 'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB', 'RCB', 'RB',
       'Crossing', 'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys',
       'Dribbling', 'Curve', 'FKAccuracy', 'LongPassing', 'BallControl',
       'Acceleration', 'SprintSpeed', 'Agility', 'Reactions', 'Balance',
       'ShotPower', 'Jumping', 'Stamina', 'Strength', 'LongShots',
       'Aggression', 'Interceptions', 'Positioning', 'Vision', 'Penalties',
       'Composure', 'Marking', 'StandingTackle', 'SlidingTackle', 'GKDiving',
       'GKHandling', 'GKKicking', 'GKPositioning', 'GKReflexes',
       'Release Clause'],
      dtype='object')

Es pot apreciar que, similarment als porters, hi ha jugadors que no tenen posició i manquen de gran part dels camps refrents a les seves estadístiques. També es podem eliminar pels mateixos motius:

In [38]:
print(str((100 * len(df[df["Position"].isna()].index)/len(df.index))) + "% del dataframe eliminat")
df = df.dropna(axis = 0, subset = ["Position"])
df[df.isna().any(axis=1)]

0.3707823507601038% del dataframe eliminat

,Age,Overall,Potential,Club,Value,Wage,International Reputation,Weak Foot,Skill Moves,Work Rate,Position,Height,Weight,LS,ST,RS,LW,LF,CF,RF,RW,LAM,CAM,RAM,LM,LCM,CM,RCM,RM,LWB,LDM,CDM,RDM,RWB,LB,LCB,CB,RCB,RB,Crossing,Finishing,HeadingAccuracy,ShortPassing,Volleys,Dribbling,Curve,FKAccuracy,LongPassing,BallControl,Acceleration,SprintSpeed,Agility,Reactions,Balance,ShotPower,Jumping,Stamina,Strength,LongShots,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
28,26,88,89,FC Bayern München,€69.5M,€315K,4.0,3.0,4.0,Medium/ Medium,LAM,5'11,172lbs,80+3,80+3,80+3,84+3,83+3,83+3,83+3,84+3,85+3,85+3,85+3,83+3,81+3,81+3,81+3,83+3,69+3,68+3,68+3,68+3,69+3,65+3,58+3,58+3,58+3,65+3,90.0,83.0,62.0,89.0,90.0,85.0,89.0,86.0,83.0,90.0,73.0,67.0,83.0,85.0,76.0,86.0,54.0,70.0,68.0,92.0,64.0,55.0,80.0,89.0,81.0,87.0,52.0,41.0,44.0,15.0,15.0,15.0,5.0,14.0,NaN
38,30,88,88,Milan,€57M,€245K,4.0,4.0,3.0,High/ Medium,LS,6'1,196lbs,85+3,85+3,85+3,81+3,83+3,83+3,83+3,81+3,80+3,80+3,80+3,78+3,71+3,71+3,71+3,78+3,55+3,53+3,53+3,53+3,55+3,51+3,48+3,48+3,48+3,51+3,68.0,92.0,80.0,75.0,90.0,84.0,74.0,62.0,59.0,85.0,73.0,73.0,75.0,86.0,69.0,86.0,79.0,70.0,85.0,80.0,50.0,20.0,92.0,74.0,70.0,86.0,35.0,22.0,18.0,5.0,12.0,7.0,5.0,10.0,NaN
91,29,85,85,Guangzhou Evergrande Taobao FC,€37M,€235K,3.0,3.0,3.0,High/ High,LDM,6'0,157lbs,81+3,81+3,81+3,79+3,81+3,81+3,81+3,79+3,81+3,81+3,81+3,79+3,82+3,82+3,82+3,79+3,78+3,81+3,81+3,81+3,78+3,78+3,80+3,80+3,80+3,78+3,64.0,81.0,85.0,84.0,75.0,82.0,66.0,72.0,80.0,84.0,73.0,73.0,69.0,84.0,66.0,83.0,90.0,92.0,81.0,80.0,81.0,81.0,84.0,78.0,71.0,80.0,75.0,81.0,73.0,16.0,16.0,11.0,6.0,8.0,NaN
166,24,83,90,Guangzhou Evergrande Taobao FC,€36.5M,€18K,2.0,4.0,4.0,High/ Medium,CAM,6'3,176lbs,80+2,80+2,80+2,81+2,81+2,81+2,81+2,81+2,81+2,81+2,81+2,80+2,79+2,79+2,79+2,80+2,69+2,69+2,69+2,69+2,69+2,67+2,64+2,64+2,64+2,67+2,78.0,80.0,77.0,81.0,76.0,82.0,86.0,87.0,79.0,84.0,77.0,76.0,76.0,79.0,65.0,84.0,58.0,76.0,72.0,88.0,67.0,58.0,86.0,81.0,71.0,74.0,55.0,62.0,42.0,13.0,11.0,13.0,12.0,10.0,NaN
176,24,83,89,Chelsea,€35M,€165K,3.0,4.0,4.0,High/ High,LCM,5'9,172lbs,71+3,71+3,71+3,79+3,78+3,78+3,78+3,79+3,81+3,81+3,81+3,80+3,82+3,82+3,82+3,80+3,76+3,78+3,78+3,78+3,76+3,74+3,69+3,69+3,69+3,74+3,73.0,62.0,42.0,87.0,76.0,88.0,78.0,68.0,82.0,89.0,84.0,74.0,81.0,70.0,85.0,79.0,63.0,82.0,65.0,75.0,77.0,78.0,69.0,88.0,59.0,72.0,69.0,75.0,63.0,9.0,5.0,6.0,7.0,7.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17978,21,51,57,Hamilton Academical FC,€50K,€3K,1.0,2.0,2.0,Medium/ Medium,ST,5'11,165lbs,49+2,49+2,49+2,49+2,49+2,49+2,49+2,49+2,47+2,47+2,47+2,47+2,40+2,40+2,40+2,47+2,34+2,31+2,31+2,31+2,34+2,33+2,30+2,30+2,30+2,33+2,34.0,53.0,44.0,38.0,40.0,50.0,39.0,26.0,33.0,48.0,64.0,74.0,56.0,49.0,65.0,42.0,62.0,48.0,60.0,43.0,35.0,16.0,47.0,45.0,62.0,49.0,14.0,13.0,13.0,12.0,13.0,16.0,9.0,14.0,NaN
17979,21,51,60,Guizhou Hengfeng FC,€60K,€2K,1.0,2.0,2.0,Medium/ Medium,CM,6'0,172lbs,49+2,49+2,49+2,50+2,50+2,50+2,50+2,50+2,50+2,50+2,50+2,51+2,50+2,50+2,50+2,51+2,50+2,50+2,50+2,50+2,50+2,50+2,49+2,49+2,49+2,50+2,36.0,30.0,48.0,57.0,32.0,45.0,37.0,38.0,55.0,50.0,71.0,76.0,75.0,55.0,58.0,55.0,60.0,62.0,61.0,33.0,58.0,41.0,53.0,47.0,36.0,43.0,47.0,41.0,46.0,12.0,12.0,10.0,13.0,9.0,NaN
18026,21,50,59,Guizhou Hengfeng FC,€50K,€2K,1.0,2.0,2.0,Medium/ Medium,LM,5'10,143lbs,44+2,44+2,44+2,47+2,46+2,46+2,46+2,47+2,48+2,48+2,48+2,49+2,48+2,48+2,48+2,49+2,50+2,50+2,50+2,50+2,50+2,51+2,50+2,50+2,50+2,51+2,41.0,28.0,50.0,54.0,26.0,50.0,39.0,40.0,55.0,46.0,61.0,77.0,76.0,50.0,74.0,47.0,63.0,50.0,52.0,29.0,56.0,50.0,37.0,49.0,42.0,38.0,46.0,48.0,51.0,15.0,8.0,10.0,13.0,7.0,NaN
18031,20,50,61,Stabæk Fotball,€40K,€2K,1.0,3.0,2.0,Medium/ Medium,RB,5'7,143lbs,37+2,37+2,37+2,42+2,40+2,40+2,40+2,42+2,39+2,39+2,39+2,43+2,38+2,38+2,38+2,43+2,48+2,43+2,43+2,43+2,48+2,48+2,45+2,45+2,45+2,48+2,46.0,29.0,35.0,32.0,26.0,52.0,32.0,28.0,22.0,34.0,60.0,58.0,57.0,47.0,85.0,29.0,64.0,64.0,32.0,29.0,54.0,54.0,43.0,38.0,38.0,32.0,51.0,48.0,48.0,11.0,7.0,9.0,10.0,6.0,NaN
18056,19,50,65,Ascoli,€60K,€3K,1.0,3.0,2.0,Medium/ Medium,CM,5'10,143lbs,44+2,44+2,44+2,47+2,45+2,45+2,45+2,47+2,47+2,47+2,47+2,49+2,48+2,48+2,48+2,49+2,52+2,51+2,51+2,51+2,52+2,52+2,51+2,51+2,51+2,52+2,50.0,30.0,50.0,54.0,40.0,50.0,40.0,40.0,50.0,50.0,62.0,63.0,60.0,52.0,65.0,50.0,64.0,52.0,54.0,40.0,60.0,49.0,26.0,49.0,40.0,42.0,41.0,54.0,55.0,8.0,11.0,13.0,14.0,14.0,NaN

Anem a veure quines  columnes ens queden encara amb NaN:

In [39]:
df.columns[df.isna().any()]

Index(['Club', 'Release Clause'], dtype='object')

Podem veure que hem arreglat la majoria de problemes que sen's presentaven respecte als NaNs llevant els porters i els jugadors sense posició, anem a veure què feim amb la resta de jugadors respecte als camps que falten per netejar:

* "Club": Suposarem que els que no tenguin un club especificat no tenen club i els donarem el valor "SenseClub".
* "Release Clause": Podem suposar que el valor d'aquesta és 0 per aquells que tenen NaN.

In [40]:
df["Club"] = df["Club"].fillna("SenseClub");
df["Release Clause"] = df["Release Clause"].fillna(0);

Anem a veure si han quedat camps NaN en el nostre dataset:

In [41]:
df.columns[df.isna().any()]

Index([], dtype='object')

Hem assegurat la completitut de les dades.

## Conversió de dades

Ara que ja no tenim NaNs, anem a arreglar les columnes que tenguin un contingut que es pugui considerar categòric i que poguem mapejar a un valor numèric.

In [42]:
df

,Age,Overall,Potential,Club,Value,Wage,International Reputation,Weak Foot,Skill Moves,Work Rate,Position,Height,Weight,LS,ST,RS,LW,LF,CF,RF,RW,LAM,CAM,RAM,LM,LCM,CM,RCM,RM,LWB,LDM,CDM,RDM,RWB,LB,LCB,CB,RCB,RB,Crossing,Finishing,HeadingAccuracy,ShortPassing,Volleys,Dribbling,Curve,FKAccuracy,LongPassing,BallControl,Acceleration,SprintSpeed,Agility,Reactions,Balance,ShotPower,Jumping,Stamina,Strength,LongShots,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,31,94,94,FC Barcelona,€110.5M,€565K,5.0,4.0,4.0,Medium/ Medium,RF,5'7,159lbs,88+2,88+2,88+2,92+2,93+2,93+2,93+2,92+2,93+2,93+2,93+2,91+2,84+2,84+2,84+2,91+2,64+2,61+2,61+2,61+2,64+2,59+2,47+2,47+2,47+2,59+2,84.0,95.0,70.0,90.0,86.0,97.0,93.0,94.0,87.0,96.0,91.0,86.0,91.0,95.0,95.0,85.0,68.0,72.0,59.0,94.0,48.0,22.0,94.0,94.0,75.0,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
1,33,94,94,Juventus,€77M,€405K,5.0,4.0,5.0,High/ Low,ST,6'2,183lbs,91+3,91+3,91+3,89+3,90+3,90+3,90+3,89+3,88+3,88+3,88+3,88+3,81+3,81+3,81+3,88+3,65+3,61+3,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3,84.0,94.0,89.0,81.0,87.0,88.0,81.0,76.0,77.0,94.0,89.0,91.0,87.0,96.0,70.0,95.0,95.0,88.0,79.0,93.0,63.0,29.0,95.0,82.0,85.0,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
2,26,92,93,Paris Saint-Germain,€118.5M,€290K,5.0,5.0,5.0,High/ Medium,LW,5'9,150lbs,84+3,84+3,84+3,89+3,89+3,89+3,89+3,89+3,89+3,89+3,89+3,88+3,81+3,81+3,81+3,88+3,65+3,60+3,60+3,60+3,65+3,60+3,47+3,47+3,47+3,60+3,79.0,87.0,62.0,84.0,84.0,96.0,88.0,87.0,78.0,95.0,94.0,90.0,96.0,94.0,84.0,80.0,61.0,81.0,49.0,82.0,56.0,36.0,89.0,87.0,81.0,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M
4,27,91,92,Manchester City,€102M,€355K,4.0,5.0,4.0,High/ High,RCM,5'11,154lbs,82+3,82+3,82+3,87+3,87+3,87+3,87+3,87+3,88+3,88+3,88+3,88+3,87+3,87+3,87+3,88+3,77+3,77+3,77+3,77+3,77+3,73+3,66+3,66+3,66+3,73+3,93.0,82.0,55.0,92.0,82.0,86.0,85.0,83.0,91.0,91.0,78.0,76.0,79.0,91.0,77.0,91.0,63.0,90.0,75.0,91.0,76.0,61.0,87.0,94.0,79.0,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M
5,27,91,91,Chelsea,€93M,€340K,4.0,4.0,4.0,High/ Medium,LF,5'8,163lbs,83+3,83+3,83+3,89+3,88+3,88+3,88+3,89+3,89+3,89+3,89+3,89+3,82+3,82+3,82+3,89+3,66+3,63+3,63+3,63+3,66+3,60+3,49+3,49+3,49+3,60+3,81.0,84.0,61.0,89.0,80.0,95.0,83.0,79.0,83.0,94.0,94.0,88.0,95.0,90.0,94.0,82.0,56.0,83.0,66.0,80.0,54.0,41.0,87.0,89.0,86.0,91.0,34.0,27.0,22.0,11.0,12.0,6.0,8.0,8.0,€172.1M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,19,47,65,Crewe Alexandra,€60K,€1K,1.0,2.0,2.0,Medium/ Medium,CM,5'9,134lbs,42+2,42+2,42+2,44+2,44+2,44+2,44+2,44+2,45+2,45+2,45+2,44+2,45+2,45+2,45+2,44+2,44+2,45+2,45+2,45+2,44+2,45+2,45+2,45+2,45+2,45+2,34.0,38.0,40.0,49.0,25.0,42.0,30.0,34.0,45.0,43.0,54.0,57.0,60.0,49.0,76.0,43.0,55.0,40.0,47.0,38.0,46.0,46.0,39.0,52.0,43.0,45.0,40.0,48.0,47.0,10.0,13.0,7.0,8.0,9.0,€143K
18203,19,47,63,Trelleborgs FF,€60K,€1K,1.0,2.0,2.0,Medium/ Medium,ST,6'3,170lbs,45+2,45+2,45+2,39+2,42+2,42+2,42+2,39+2,40+2,40+2,40+2,38+2,35+2,35+2,35+2,38+2,30+2,31+2,31+2,31+2,30+2,29+2,32+2,32+2,32+2,29+2,23.0,52.0,52.0,43.0,36.0,39.0,32.0,20.0,25.0,40.0,41.0,39.0,38.0,40.0,52.0,41.0,47.0,43.0,67.0,42.0,47.0,16.0,46.0,33.0,43.0,42.0,22.0,15.0,19.0,10.0,9.0,9.0,5.0,12.0,€113K
18204,16,47,67,Cambridge United,€60K,€1K,1.0,3.0,2.0,Medium/ Medium,ST,5'8,148lbs,45+2,45+2,45+2,45+2,46+2,46+2,46+2,45+2,44+2,44+2,44+2,44+2,38+2,38+2,38+2,44+2,34+2,30+2,30+2,30+2,34+2,33+2,28+2,28+2,28+2,33+2,25.0,40.0,46.0,38.0,38.0,45.0,38.0,27.0,28.0,44.0,70.0,69.0,50.0,47.0,58.0,45.0,60.0,55.0,32.0,45.0,32.0,15.0,48.0,43.0,55.0,41.0,32.0,13.0,11.0,6.0,5.0,10.0,6.0,13.0,€165K
18205,17,47,66,Tranmere Rovers,€60K,€1K,1.0,3.0,2.0,Medium/ Medium,RW,5'10,154lbs,47+2,47+2,47+2,47+2,46+2,46+2,46+2,47+2,45+2,45+2,45+2,46+2,39+2,39+2,39+2,46+2,36+2,32+2,32+2,32+2,36+2,35+2,31+2,31+2,31+2,35+2,44.0,50.0,39.0,42.0,40.0,51.0,34.0,32.0,32.0,52.0,61.0,60.0,52.0,21.0,71.0,64.0,42.0,40.0,48.0,34.0,33.0,22.0,44.0,47.0,50.0,46.0,20.0,25.0,27.0,14.0,6.0,14.0,8.0,9.0,€143K
18206,16,46,66,Tranmere Rovers,€60K,€1K,1.0,3.0,2.0,Medium/ Medium,CM,5'10,176lbs,43+2,43+2,43+2,45+2,44+2,44+2,44+2,45+2,45+2,45+2,45+2,46+2,45+2,45+2,45+2,46+2,46+2,46+2,46+2,46+2,46+2,46+2,47+2,47+2,47+2,46+2,41.0,34.0,46.0,48.0,30.0,43.0,40.0,34.0,44.0,51.0,57.0,55.0,55.0,51.0,63.0,43.0,62.0,47.0,60.0,32.0,56.0,42.0,34.0,49.0,33.0,43.0,40.0,43.0,50.0,10.0,15.0,9.0,12.0,9.0,€165K

Ara duim a terme les declaracions de les funcions de neteja de dades per aquestes dades de tipus diferent a int o float que són fàcilment convertibles a aquests tipus llevant les unitats de mesura ("Value", "Release Clause", "Wage", "Height", "Weight") i calculant les expressions calculables ("LS" fins a "RB"):

In [43]:
#Per "Value", "Release Clause" i "Wage"
def money_to_float(x): 
    if type(x) == float or type(x) == int:
        return float(x)
    else:
        ret_val = 0.0
        x = x.replace("€", "")
        if 'K' in x:
            if len(x) > 1:
                ret_val = float(x.replace('K', ''))
            ret_val = ret_val *1000
        if 'M' in x:
            if len(x) > 1:
                ret_val = float(x.replace('M', ''))
            ret_val = ret_val * 1000000.0
        return ret_val

#Per l'altura
def height_to_float(x): 
    return float(x.replace("'", "."))

#Pel pes
def weight_to_float(x): 
    return float(x.replace("lbs", ""))

#Pels valors de forma [int]+[int]
def suma_to_float(x): 
    ll = x.split("+")
    return float(ll[0]) + float(ll[1])

Apliquem les funcions als camps esperats:

In [44]:
df["Value"] = df["Value"].apply(money_to_float)
df["Wage"] = df["Wage"].apply(money_to_float)
df["Release Clause"] = df["Release Clause"].apply(money_to_float)

df["Height"] = df["Height"].apply(height_to_float)

df["Weight"] = df["Weight"].apply(weight_to_float)

sub = ["LS", "ST", "RS", "LW", "LF", "CF", "RF", "RW", "LAM", "CAM", "RAM", "LM", "LCM", "CM", "RCM", "RM", "LWB", "LDM", 
       "CDM", "RDM", "RWB", "LB", "LCB", "CB", "RCB", "RB"]
for col in sub:
    df[col] = df[col].apply(suma_to_float)

df

,Age,Overall,Potential,Club,Value,Wage,International Reputation,Weak Foot,Skill Moves,Work Rate,Position,Height,Weight,LS,ST,RS,LW,LF,CF,RF,RW,LAM,CAM,RAM,LM,LCM,CM,RCM,RM,LWB,LDM,CDM,RDM,RWB,LB,LCB,CB,RCB,RB,Crossing,Finishing,HeadingAccuracy,ShortPassing,Volleys,Dribbling,Curve,FKAccuracy,LongPassing,BallControl,Acceleration,SprintSpeed,Agility,Reactions,Balance,ShotPower,Jumping,Stamina,Strength,LongShots,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,31,94,94,FC Barcelona,110500000.0,565000.0,5.0,4.0,4.0,Medium/ Medium,RF,5.70,159.0,90.0,90.0,90.0,94.0,95.0,95.0,95.0,94.0,95.0,95.0,95.0,93.0,86.0,86.0,86.0,93.0,66.0,63.0,63.0,63.0,66.0,61.0,49.0,49.0,49.0,61.0,84.0,95.0,70.0,90.0,86.0,97.0,93.0,94.0,87.0,96.0,91.0,86.0,91.0,95.0,95.0,85.0,68.0,72.0,59.0,94.0,48.0,22.0,94.0,94.0,75.0,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,226500000.0
1,33,94,94,Juventus,77000000.0,405000.0,5.0,4.0,5.0,High/ Low,ST,6.20,183.0,94.0,94.0,94.0,92.0,93.0,93.0,93.0,92.0,91.0,91.0,91.0,91.0,84.0,84.0,84.0,91.0,68.0,64.0,64.0,64.0,68.0,64.0,56.0,56.0,56.0,64.0,84.0,94.0,89.0,81.0,87.0,88.0,81.0,76.0,77.0,94.0,89.0,91.0,87.0,96.0,70.0,95.0,95.0,88.0,79.0,93.0,63.0,29.0,95.0,82.0,85.0,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,127100000.0
2,26,92,93,Paris Saint-Germain,118500000.0,290000.0,5.0,5.0,5.0,High/ Medium,LW,5.90,150.0,87.0,87.0,87.0,92.0,92.0,92.0,92.0,92.0,92.0,92.0,92.0,91.0,84.0,84.0,84.0,91.0,68.0,63.0,63.0,63.0,68.0,63.0,50.0,50.0,50.0,63.0,79.0,87.0,62.0,84.0,84.0,96.0,88.0,87.0,78.0,95.0,94.0,90.0,96.0,94.0,84.0,80.0,61.0,81.0,49.0,82.0,56.0,36.0,89.0,87.0,81.0,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,228100000.0
4,27,91,92,Manchester City,102000000.0,355000.0,4.0,5.0,4.0,High/ High,RCM,5.11,154.0,85.0,85.0,85.0,90.0,90.0,90.0,90.0,90.0,91.0,91.0,91.0,91.0,90.0,90.0,90.0,91.0,80.0,80.0,80.0,80.0,80.0,76.0,69.0,69.0,69.0,76.0,93.0,82.0,55.0,92.0,82.0,86.0,85.0,83.0,91.0,91.0,78.0,76.0,79.0,91.0,77.0,91.0,63.0,90.0,75.0,91.0,76.0,61.0,87.0,94.0,79.0,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,196400000.0
5,27,91,91,Chelsea,93000000.0,340000.0,4.0,4.0,4.0,High/ Medium,LF,5.80,163.0,86.0,86.0,86.0,92.0,91.0,91.0,91.0,92.0,92.0,92.0,92.0,92.0,85.0,85.0,85.0,92.0,69.0,66.0,66.0,66.0,69.0,63.0,52.0,52.0,52.0,63.0,81.0,84.0,61.0,89.0,80.0,95.0,83.0,79.0,83.0,94.0,94.0,88.0,95.0,90.0,94.0,82.0,56.0,83.0,66.0,80.0,54.0,41.0,87.0,89.0,86.0,91.0,34.0,27.0,22.0,11.0,12.0,6.0,8.0,8.0,172100000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,19,47,65,Crewe Alexandra,60000.0,1000.0,1.0,2.0,2.0,Medium/ Medium,CM,5.90,134.0,44.0,44.0,44.0,46.0,46.0,46.0,46.0,46.0,47.0,47.0,47.0,46.0,47.0,47.0,47.0,46.0,46.0,47.0,47.0,47.0,46.0,47.0,47.0,47.0,47.0,47.0,34.0,38.0,40.0,49.0,25.0,42.0,30.0,34.0,45.0,43.0,54.0,57.0,60.0,49.0,76.0,43.0,55.0,40.0,47.0,38.0,46.0,46.0,39.0,52.0,43.0,45.0,40.0,48.0,47.0,10.0,13.0,7.0,8.0,9.0,143000.0
18203,19,47,63,Trelleborgs FF,60000.0,1000.0,1.0,2.0,2.0,Medium/ Medium,ST,6.30,170.0,47.0,47.0,47.0,41.0,44.0,44.0,44.0,41.0,42.0,42.0,42.0,40.0,37.0,37.0,37.0,40.0,32.0,33.0,33.0,33.0,32.0,31.0,34.0,34.0,34.0,31.0,23.0,52.0,52.0,43.0,36.0,39.0,32.0,20.0,25.0,40.0,41.0,39.0,38.0,40.0,52.0,41.0,47.0,43.0,67.0,42.0,47.0,16.0,46.0,33.0,43.0,42.0,22.0,15.0,19.0,10.0,9.0,9.0,5.0,12.0,113000.0
18204,16,47,67,Cambridge United,60000.0,1000.0,1.0,3.0,2.0,Medium/ Medium,ST,5.80,148.0,47.0,47.0,47.0,47.0,48.0,48.0,48.0,47.0,46.0,46.0,46.0,46.0,40.0,40.0,40.0,46.0,36.0,32.0,32.0,32.0,36.0,35.0,30.0,30.0,30.0,35.0,25.0,40.0,46.0,38.0,38.0,45.0,38.0,27.0,28.0,44.0,70.0,69.0,50.0,47.0,58.0,45.0,60.0,55.0,32.0,45.0,32.0,15.0,48.0,43.0,55.0,41.0,32.0,13.0,11.0,6.0,5.0,10.0,6.0,13.0,165000.0
18205,17,47,66,Tranmere Rovers,60000.0,1000.0,1.0,3.0,2.0,Medium/ Medium,RW,5.10,154.0,49.0,49.0,49.0,49.0,48.0,48.0,48.0,49.0,47.0,47.0,47.0,48.0,41.0,41.0,41.0,48.0,38.0,34.0,34.0,34.0,38.0,37.0,33.0,33.0,33.0,37.0,44.0,50.0,39.0,42.0,40.0,51.0,34.0,32.0,32.0,52.0,61.0,60.0,52.0,21.0,71.0,64.0,42.0,40.0,48.0,34.0,33.0,22.0,44.0,47.0,50.0,46.0,20.0,25.0,27.0,14.0,6.0,14.0,8.0,9.0,143000.0
18206,16,46,66,Tranmere Rovers,60000.0,1000.0,1.0,3.0,2.0,Medium/ Medium,CM,5.10,176.0,45.0,45.0,45.0,47.0,46.0,46.0,46.0,47.0,47.0,47.0,47.0,48.0,47.0,47.0,47.0,48.0,48.0,48.0,48.0,48.0,48.0,48.0,49.0,49.0,49.0,48.0,41.0,34.0,46.0,48.0,30.0,43.0,40.0,34.0,44.0,51.0,57.0,55.0,55.0,51.0,63.0,43.0,62.0,47.0,60.0,32.0,56.0,42.0,34.0,49.0,33.0,43.0,40.0,43.0,50.0,10.0,15.0,9.0,12.0,9.0,165000.0

Si ens fixam bé "Work Rate" indica la capacitat ofensiva i defensiva del jugador amb format "capacitat ofensiva"/"capacitat defensiva". Es tracten d'unes dades categòriques. També es pot apreciar que es poden separar en dues columnes aquestes dades, una per la capacitat ofensiva i una altra per la defensiva. També podem associar un valor major a una major puntuació d'ofensivitat o defensivitat:
* Low es mapeja a 1
* Medium es mapeja a 2
* High es mapeja a 3

Apliquem les operacions necessàries

In [45]:
def to_float_wr(x):
    x = x.replace(" ","")
    if x == "Low":
        return 1.0
    elif x == "Medium":
        return 2.0
    elif x == "High": 
        return 3.0
    return 0.0

def offensives_defensives(wr, ofensives, defensives):
    for x in wr:
        ll = x.split("/")
        ofensives.append(to_float_wr(ll[0]))
        defensives.append(to_float_wr(ll[1]))
        
ofensives = []
defensives = []
offensives_defensives(df["Work Rate"], ofensives, defensives)
df.insert(13, "Defensivitat", defensives, False)
df.insert(13, "Ofensivitat", ofensives, False)
df = df.drop(['Work Rate'], axis=1)

df

,Age,Overall,Potential,Club,Value,Wage,International Reputation,Weak Foot,Skill Moves,Position,Height,Weight,Ofensivitat,Defensivitat,LS,ST,RS,LW,LF,CF,RF,RW,LAM,CAM,RAM,LM,LCM,CM,RCM,RM,LWB,LDM,CDM,RDM,RWB,LB,LCB,CB,RCB,RB,Crossing,Finishing,HeadingAccuracy,ShortPassing,Volleys,Dribbling,Curve,FKAccuracy,LongPassing,BallControl,Acceleration,SprintSpeed,Agility,Reactions,Balance,ShotPower,Jumping,Stamina,Strength,LongShots,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,31,94,94,FC Barcelona,110500000.0,565000.0,5.0,4.0,4.0,RF,5.70,159.0,2.0,2.0,90.0,90.0,90.0,94.0,95.0,95.0,95.0,94.0,95.0,95.0,95.0,93.0,86.0,86.0,86.0,93.0,66.0,63.0,63.0,63.0,66.0,61.0,49.0,49.0,49.0,61.0,84.0,95.0,70.0,90.0,86.0,97.0,93.0,94.0,87.0,96.0,91.0,86.0,91.0,95.0,95.0,85.0,68.0,72.0,59.0,94.0,48.0,22.0,94.0,94.0,75.0,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,226500000.0
1,33,94,94,Juventus,77000000.0,405000.0,5.0,4.0,5.0,ST,6.20,183.0,3.0,1.0,94.0,94.0,94.0,92.0,93.0,93.0,93.0,92.0,91.0,91.0,91.0,91.0,84.0,84.0,84.0,91.0,68.0,64.0,64.0,64.0,68.0,64.0,56.0,56.0,56.0,64.0,84.0,94.0,89.0,81.0,87.0,88.0,81.0,76.0,77.0,94.0,89.0,91.0,87.0,96.0,70.0,95.0,95.0,88.0,79.0,93.0,63.0,29.0,95.0,82.0,85.0,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,127100000.0
2,26,92,93,Paris Saint-Germain,118500000.0,290000.0,5.0,5.0,5.0,LW,5.90,150.0,3.0,2.0,87.0,87.0,87.0,92.0,92.0,92.0,92.0,92.0,92.0,92.0,92.0,91.0,84.0,84.0,84.0,91.0,68.0,63.0,63.0,63.0,68.0,63.0,50.0,50.0,50.0,63.0,79.0,87.0,62.0,84.0,84.0,96.0,88.0,87.0,78.0,95.0,94.0,90.0,96.0,94.0,84.0,80.0,61.0,81.0,49.0,82.0,56.0,36.0,89.0,87.0,81.0,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,228100000.0
4,27,91,92,Manchester City,102000000.0,355000.0,4.0,5.0,4.0,RCM,5.11,154.0,3.0,3.0,85.0,85.0,85.0,90.0,90.0,90.0,90.0,90.0,91.0,91.0,91.0,91.0,90.0,90.0,90.0,91.0,80.0,80.0,80.0,80.0,80.0,76.0,69.0,69.0,69.0,76.0,93.0,82.0,55.0,92.0,82.0,86.0,85.0,83.0,91.0,91.0,78.0,76.0,79.0,91.0,77.0,91.0,63.0,90.0,75.0,91.0,76.0,61.0,87.0,94.0,79.0,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,196400000.0
5,27,91,91,Chelsea,93000000.0,340000.0,4.0,4.0,4.0,LF,5.80,163.0,3.0,2.0,86.0,86.0,86.0,92.0,91.0,91.0,91.0,92.0,92.0,92.0,92.0,92.0,85.0,85.0,85.0,92.0,69.0,66.0,66.0,66.0,69.0,63.0,52.0,52.0,52.0,63.0,81.0,84.0,61.0,89.0,80.0,95.0,83.0,79.0,83.0,94.0,94.0,88.0,95.0,90.0,94.0,82.0,56.0,83.0,66.0,80.0,54.0,41.0,87.0,89.0,86.0,91.0,34.0,27.0,22.0,11.0,12.0,6.0,8.0,8.0,172100000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,19,47,65,Crewe Alexandra,60000.0,1000.0,1.0,2.0,2.0,CM,5.90,134.0,2.0,2.0,44.0,44.0,44.0,46.0,46.0,46.0,46.0,46.0,47.0,47.0,47.0,46.0,47.0,47.0,47.0,46.0,46.0,47.0,47.0,47.0,46.0,47.0,47.0,47.0,47.0,47.0,34.0,38.0,40.0,49.0,25.0,42.0,30.0,34.0,45.0,43.0,54.0,57.0,60.0,49.0,76.0,43.0,55.0,40.0,47.0,38.0,46.0,46.0,39.0,52.0,43.0,45.0,40.0,48.0,47.0,10.0,13.0,7.0,8.0,9.0,143000.0
18203,19,47,63,Trelleborgs FF,60000.0,1000.0,1.0,2.0,2.0,ST,6.30,170.0,2.0,2.0,47.0,47.0,47.0,41.0,44.0,44.0,44.0,41.0,42.0,42.0,42.0,40.0,37.0,37.0,37.0,40.0,32.0,33.0,33.0,33.0,32.0,31.0,34.0,34.0,34.0,31.0,23.0,52.0,52.0,43.0,36.0,39.0,32.0,20.0,25.0,40.0,41.0,39.0,38.0,40.0,52.0,41.0,47.0,43.0,67.0,42.0,47.0,16.0,46.0,33.0,43.0,42.0,22.0,15.0,19.0,10.0,9.0,9.0,5.0,12.0,113000.0
18204,16,47,67,Cambridge United,60000.0,1000.0,1.0,3.0,2.0,ST,5.80,148.0,2.0,2.0,47.0,47.0,47.0,47.0,48.0,48.0,48.0,47.0,46.0,46.0,46.0,46.0,40.0,40.0,40.0,46.0,36.0,32.0,32.0,32.0,36.0,35.0,30.0,30.0,30.0,35.0,25.0,40.0,46.0,38.0,38.0,45.0,38.0,27.0,28.0,44.0,70.0,69.0,50.0,47.0,58.0,45.0,60.0,55.0,32.0,45.0,32.0,15.0,48.0,43.0,55.0,41.0,32.0,13.0,11.0,6.0,5.0,10.0,6.0,13.0,165000.0
18205,17,47,66,Tranmere Rovers,60000.0,1000.0,1.0,3.0,2.0,RW,5.10,154.0,2.0,2.0,49.0,49.0,49.0,49.0,48.0,48.0,48.0,49.0,47.0,47.0,47.0,48.0,41.0,41.0,41.0,48.0,38.0,34.0,34.0,34.0,38.0,37.0,33.0,33.0,33.0,37.0,44.0,50.0,39.0,42.0,40.0,51.0,34.0,32.0,32.0,52.0,61.0,60.0,52.0,21.0,71.0,64.0,42.0,40.0,48.0,34.0,33.0,22.0,44.0,47.0,50.0,46.0,20.0,25.0,27.0,14.0,6.0,14.0,8.0,9.0,143000.0
18206,16,46,66,Tranmere Rovers,60000.0,1000.0,1.0,3.0,2.0,CM,5.10,176.0,2.0,2.0,45.0,45.0,45.0,47.0,46.0,46.0,46.0,47.0,47.0,47.0,47.0,48.0,47.0,47.0,47.0,48.0,48.0,48.0,48.0,48.0,48.0,48.0,49.0,49.0,49.0,48.0,41.0,34.0,46.0,48.0,30.0,43.0,40.0,34.0,44.0,51.0,57.0,55.0,55.0,51.0,63.0,43.0,62.0,47.0,60.0,32.0,56.0,42.0,34.0,49.0,33.0,43.0,40.0,43.0,50.0,10.0,15.0,9.0,12.0,9.0,165000.0

Ara anem a aplicar <a href = "https://es.wikipedia.org/wiki/One-hot">*One Hot Encoding*</a> sobre les dades categòriques que queden per processar -Club i Position- (O ets del FC Barcelona o no, si es discretitza el club assignant un nombre arbitrari a cada club tenim clubs que tenen un valor gros assignat i altres amb un de petit. Si prenem una transformació quantitativa amb aquesta variable respecte la regressió lieal l'únic que aconseguiriem és generar renou. És millor fer una classificació binària: pertany/no pertany. Això també s'aplica a la resta de dades categòriques esmentades anteriorment):

In [46]:
clb = df.pop("Club")
df = pandas.concat([df.reset_index(drop=True), pandas.get_dummies(clb, prefix='clb').reset_index(drop=True)], axis=1, sort=False)

pos = df.pop("Position")
df = pandas.concat([df.reset_index(drop=True), pandas.get_dummies(pos, prefix='pos').reset_index(drop=True)], axis=1, sort=False)

df

,Age,Overall,Potential,Value,Wage,International Reputation,Weak Foot,Skill Moves,Height,Weight,Ofensivitat,Defensivitat,LS,ST,RS,LW,LF,CF,RF,RW,LAM,CAM,RAM,LM,LCM,CM,RCM,RM,LWB,LDM,CDM,RDM,RWB,LB,LCB,CB,RCB,RB,Crossing,Finishing,HeadingAccuracy,ShortPassing,Volleys,Dribbling,Curve,FKAccuracy,LongPassing,BallControl,Acceleration,SprintSpeed,Agility,Reactions,Balance,ShotPower,Jumping,Stamina,Strength,LongShots,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause,clb_ SSV Jahn Regensburg,clb_1. FC Heidenheim 1846,clb_1. FC Kaiserslautern,clb_1. FC Köln,clb_1. FC Magdeburg,clb_1. FC Nürnberg,clb_1. FC Union Berlin,clb_1. FSV Mainz 05,clb_AC Ajaccio,clb_AC Horsens,clb_AD Alcorcón,clb_ADO Den Haag,clb_AEK Athens,clb_AFC Wimbledon,clb_AIK,clb_AJ Auxerre,clb_AS Béziers,clb_AS Monaco,clb_AS Nancy Lorraine,clb_AS Saint-Étienne,clb_AZ Alkmaar,clb_Aalborg BK,clb_Aarhus GF,clb_Aberdeen,clb_Accrington Stanley,clb_Adelaide United,clb_Ajax,clb_Akhisar Belediyespor,clb_Al Ahli,clb_Al Batin,clb_Al Faisaly,clb_Al Fateh,clb_Al Fayha,clb_Al Hazem,clb_Al Hilal,clb_Al Ittihad,clb_Al Nassr,clb_Al Qadisiyah,clb_Al Raed,clb_Al Shabab,clb_Al Taawoun,clb_Al Wehda,clb_Alanyaspor,clb_Albacete BP,clb_Alianza Petrolera,clb_Amiens SC,clb_América FC (Minas Gerais),clb_América de Cali,clb_Angers SCO,clb_Antalyaspor,clb_Argentinos Juniors,clb_Arka Gdynia,clb_Arsenal,clb_Ascoli,clb_Aston Villa,clb_Atalanta,clb_Athletic Club de Bilbao,clb_Atiker Konyaspor,clb_Atlanta United,clb_Atlético Bucaramanga,clb_Atlético Huila,clb_Atlético Madrid,clb_Atlético Mineiro,clb_Atlético Nacional,clb_Atlético Paranaense,clb_Atlético Tucumán,clb_Audax Italiano,clb_BB Erzurumspor,clb_BK Häcken,clb_BSC Young Boys,clb_Bahia,clb_Barnsley,clb_Bayer 04 Leverkusen,clb_Beijing Renhe FC,clb_Beijing Sinobo Guoan FC,clb_Belgrano de Córdoba,clb_Benevento,clb_Beşiktaş JK,clb_Birmingham City,clb_Blackburn Rovers,clb_Blackpool,clb_Boavista FC,clb_Boca Juniors,clb_Bohemian FC,clb_Bologna,clb_Bolton Wanderers,clb_Borussia Dortmund,clb_Borussia Mönchengladbach,clb_Botafogo,clb_Bournemouth,clb_Boyacá Chicó FC,clb_Bradford City,clb_Bray Wanderers,clb_Brentford,clb_Brescia,clb_Brighton & Hove Albion,clb_Brisbane Roar,clb_Bristol City,clb_Bristol Rovers,clb_Brøndby IF,clb_Burnley,clb_Bursaspor,clb_Burton Albion,clb_Bury,clb_CA Osasuna,clb_CD Antofagasta,clb_CD Aves,clb_CD Everton de Viña del Mar,clb_CD Feirense,clb_CD Huachipato,clb_CD Leganés,clb_CD Lugo,clb_CD Nacional,clb_CD Numancia,clb_CD O'Higgins,clb_CD Palestino,clb_CD Tenerife,clb_CD Tondela,clb_CD Universidad de Concepción,clb_CF Rayo Majadahonda,clb_CF Reus Deportiu,clb_Cagliari,clb_Cambridge United,clb_Cardiff City,clb_Carlisle United,clb_Carpi,clb_Ceará Sporting Club,clb_Celtic,clb_Central Coast Mariners,clb_Cerezo Osaka,clb_Chamois Niortais Football Club,clb_Changchun Yatai FC,clb_Chapecoense,clb_Charlton Athletic,clb_Chelsea,clb_Cheltenham Town,clb_Chicago Fire,clb_Chievo Verona,clb_Chongqing Dangdai Lifan FC SWM Team,clb_Cittadella,clb_Clermont Foot 63,clb_Club América,clb_Club Atlas,clb_Club Atlético Aldosivi,clb_Club Atlético Banfield,clb_Club Atlético Colón,clb_Club Atlético Huracán,clb_Club Atlético Lanús,clb_Club Atlético Talleres,clb_Club Atlético Tigre,clb_Club Brugge KV,clb_Club Deportes Temuco,clb_Club León,clb_Club Necaxa,clb_Club Tijuana,clb_Clube Sport Marítimo,clb_Colchester United,clb_Colo-Colo,clb_Colorado Rapids,clb_Columbus Crew SC,clb_Cork City,clb_Cosenza,clb_Coventry City,clb_Cracovia,clb_Crawley Town,clb_Crewe Alexandra,clb_Crotone,clb_Cruz Azul,clb_Cruzeiro,clb_Crystal Palace,clb_Curicó Unido,clb_Cádiz CF,clb_Córdoba CF,clb_DC United,clb_DSC Arminia Bielefeld,clb_Daegu FC,clb_Dalian YiFang FC,clb_Dalkurd FF,clb_De Graafschap,clb_Defensa y Justicia,clb_Deportes Iquique,clb_Deportes Tolima,clb_Deportivo Alavés,clb_Deportivo Cali,clb_Deportivo Pasto,clb_Deportivo Toluca,clb_Deportivo de La Coruña,clb_Derby County,clb_Derry City,clb_Dijon FCO,clb_Dinamo Zagreb,clb_Djurgårdens IF,clb_Doncaster Rovers,clb_Dundalk,clb_Dundee FC,clb_Dynamo Kyiv,clb_ESTAC Troyes,clb_Eintracht Braunschweig,clb_Eintracht Frankfurt,clb_Elche CF,clb_Empoli,clb_En Avant de Guingamp,clb_Envigado FC,clb_Esbjerg fB,clb_Estudiantes de La Plata,clb_Ettifaq FC,clb_Everton,clb_Excelsior,clb_Exeter City,clb_Extremadura UD,clb_FC Admira Wacker Mödling,clb_FC Augsburg,clb_FC Barcelona,clb_FC Basel 1893,clb_FC Bayern München,clb_FC Carl Zeiss Jena,clb_FC Dallas,clb_FC Emmen,clb_FC Energie Cottbus,clb_FC Erzgebirge Aue,clb_FC Girondins de Bordeaux,clb_FC Groningen,clb_FC Hansa Rostock,clb_FC Ingolstadt 04,clb_FC København,clb_FC Lorient,clb_FC Lugano,clb_FC Luzern,clb_FC Metz,clb_FC Midtjylland,clb_FC Nantes,clb_FC Nordsjælland,clb_FC Porto,clb_FC Red Bull Salzburg,clb_FC Schalke 04,clb_FC Seoul,clb_FC Sion,clb_FC Sochaux-Montbéliard,clb_FC St. Gallen,clb_FC St. Pauli,clb_FC Thun,clb_FC Tokyo,clb_FC Utrecht,clb_FC Wacker Innsbruck,clb_FC Würzburger Kickers,clb_FC Zürich,clb_FK Austria Wien,clb_FK Bodø/Glimt,clb_FK Haugesund,clb_FSV Zwickau,clb_Fenerbahçe SK,clb_Feyenoord,clb_Fiorentina,clb_Fleetwood Town,clb_Fluminense,clb_Foggia,clb_Forest Green Rovers,clb_Fortuna Düsseldorf,clb_Fortuna Sittard,clb_Frosinone,clb_Fulham,clb_GD Chaves,clb_GFC Ajaccio,clb_GIF Sundsvall,clb_Galatasaray SK,clb_Gamba Osaka,clb_Gangwon FC,clb_Genoa,clb_Getafe CF,clb_Gillingham,clb_Gimnasia y Esgrima La Plata,clb_Gimnàstic de Tarragona,clb_Girona FC,clb_Godoy Cruz,clb_Granada CF,clb_Grasshopper Club Zürich,clb_Grenoble Foot 38,clb_Grimsby Town,clb_Grêmio,clb_Guadalajara,clb_Guangzhou Evergrande Taobao FC,clb_Guangzhou R&F; FC,clb_Guizhou Hengfeng FC,clb_Gyeongnam FC,clb_Górnik Zabrze,clb_Göztepe SK,clb_HJK Helsinki,clb_Hallescher FC,clb_Hamburger SV,clb_Hamilton Academical FC,clb_Hammarby IF,clb_Hannover 96,clb_Heart of Midlothian,clb_Hebei China Fortune FC,clb_Hellas Verona,clb_Henan Jianye FC,clb_Heracles Almelo,clb_Hertha BSC,clb_Hibernian,clb_Hobro IK,clb_Hokkaido Consadole Sapporo,clb_Holstein Kiel,clb_Houston Dynamo,clb_Huddersfield Town,clb_Hull City,clb_IF Brommapojkarna,clb_IF Elfsborg,clb_IFK Göteborg,clb_IFK Norrköping,clb_IK Sirius,clb_IK Start,clb_Incheon United FC,clb_Independiente,clb_Independiente Medellín,clb_Independiente Santa Fe,clb_Inter,clb_Internacional,clb_Ipswich Town,clb_Itagüí Leones FC,clb_Jagiellonia Białystok,clb_Jaguares de Córdoba,clb_Jeju United FC,clb_Jeonbuk Hyundai Motors,clb_Jeonnam Dragons,clb_Jiangsu Suning FC,clb_Junior FC,clb_Juventus,clb_Júbilo Iwata,clb_KAA Gent,clb_KAS Eupen,clb_KFC Uerdingen 05,clb_KRC Genk,clb_KSV Cercle Brugge,clb_KV Kortrijk,clb_KV Oostende,clb_Kaizer Chiefs,clb_Kalmar FF,clb_Karlsruher SC,clb_Kashima Antlers,clb_Kashiwa Reysol,clb_Kasimpaşa SK,clb_Kawasaki Frontale,clb_Kayserispor,clb_Kilmarnock,clb_Korona Kielce,clb_Kristiansund BK,clb_LA Galaxy,clb_LASK Linz,clb_LOSC Lille,clb_La Berrichonne de Châteauroux,clb_La Equidad,clb_Lazio,clb_Le Havre AC,clb_Lecce,clb_Lech Poznań,clb_Lechia Gdańsk,clb_Leeds United,clb_Legia Warszawa,clb_Leicester City,clb_Levante UD,clb_Lillestrøm SK,clb_Limerick FC,clb_Lincoln City,clb_Liverpool,clb_Livingston FC,clb_Livorno,clb_Lobos BUAP,clb_Lokomotiv Moscow,clb_Los Angeles FC,clb_Luton Town,clb_MKE Ankaragücü,clb_MSV Duisburg,clb_Macclesfield Town,clb_Malmö FF,clb_Manchester City,clb_Manchester United,clb_Mansfield Town,clb_Medipol Başakşehir FK,clb_Melbourne City FC,clb_Melbourne Victory,clb_Middlesbrough,clb_Miedź Legnica,clb_Milan,clb_Millonarios FC,clb_Millwall,clb_Milton Keynes Dons,clb_Minnesota United FC,clb_Molde FK,clb_Monarcas Morelia,clb_Monterrey,clb_Montpellier HSC,clb_Montreal Impact,clb_Morecambe,clb_Moreirense FC,clb_Motherwell,clb_Málaga CF,clb_NAC Breda,clb_Nagoya Grampus,clb_Napoli,clb_Neuchâtel Xamax,clb_New England Revolution,clb_New York City FC,clb_New York Red Bulls,clb_Newcastle Jets,clb_Newcastle United,clb_Newell's Old Boys,clb_Newport County,clb_Northampton Town,clb_Norwich City,clb_Nottingham Forest,clb_Notts County,clb_Nîmes Olympique,clb_OGC Nice,clb_Odds BK,clb_Odense Boldklub,clb_Ohod Club,clb_Oldham Athletic,clb_Olympiacos CFP,clb_Olympique Lyonnais,clb_Olympique de Marseille,clb_Once Caldas,clb_Orlando City SC,clb_Orlando Pirates,clb_Os Belenenses,clb_Oxford United,clb_PAOK,clb_PEC Zwolle,clb_PFC CSKA Moscow,clb_PSV,clb_Pachuca,clb_Padova,clb_Palermo,clb_Panathinaikos FC,clb_Paraná,clb_Paris FC,clb_Paris Saint-Germain,clb_Parma,clb_Patriotas Boyacá FC,clb_Patronato,clb_Perth Glory,clb_Perugia,clb_Pescara,clb_Peterborough United,clb_Philadelphia Union,clb_Piast Gliwice,clb_Plymouth Argyle,clb_Pogoń Szczecin,clb_Pohang Steelers,clb_Port Vale,clb_Portimonense SC,clb_Portland Timbers,clb_Portsmouth,clb_Preston North End,clb_Puebla FC,clb_Queens Park Rangers,clb_Querétaro,clb_RB Leipzig,clb_RC Celta,clb_RC Strasbourg Alsace,clb_RCD Espanyol,clb_RCD Mallorca,clb_RSC Anderlecht,clb_Racing Club,clb_Racing Club de Lens,clb_Randers FC,clb_Rangers FC,clb_Ranheim Fotball,clb_Rayo Vallecano,clb_Reading,clb_Real Betis,clb_Real Madrid,clb_Real Oviedo,clb_Real Salt Lake,clb_Real Sociedad,clb_Real Sporting de Gijón,clb_Real Valladolid CF,clb_Real Zaragoza,clb_Red Star FC,clb_Rio Ave FC,clb_Rionegro Águilas,clb_River Plate,clb_Rochdale,clb_Roma,clb_Rosario Central,clb_Rosenborg BK,clb_Rotherham United,clb_Royal Antwerp FC,clb_Royal Excel Mouscron,clb_SC Braga,clb_SC Fortuna Köln,clb_SC Freiburg,clb_SC Heerenveen,clb_SC Paderborn 07,clb_SC Preußen Münster,clb_SCR Altach,clb_SD Eibar,clb_SD Huesca,clb_SG Dynamo Dresden,clb_SG Sonnenhof Großaspach,clb_SK Brann,clb_SK Rapid Wien,clb_SK Slavia Praha,clb_SK Sturm Graz,clb_SKN St. Pölten,clb_SL Benfica,clb_SPAL,clb_SV Darmstadt 98,clb_SV Mattersburg,clb_SV Meppen,clb_SV Sandhausen,clb_SV Wehen Wiesbaden,clb_SV Werder Bremen,clb_SV Zulte-Waregem,clb_Sagan Tosu,clb_Sampdoria,clb_San Jose Earthquakes,clb_San Lorenzo de Almagro,clb_San Luis de Quillota,clb_San Martin de Tucumán,clb_San Martín de San Juan,clb_Sandefjord Fotball,clb_Sanfrecce Hiroshima,clb_Sangju Sangmu FC,clb_Santa Clara,clb_Santos,clb_Santos Laguna,clb_Sarpsborg 08 FF,clb_Sassuolo,clb_Scunthorpe United,clb_Seattle Sounders FC,clb_SenseClub,clb_Sevilla FC,clb_Shakhtar Donetsk,clb_Shamrock Rovers,clb_Shandong Luneng TaiShan FC,clb_Shanghai Greenland Shenhua FC,clb_Shanghai SIPG FC,clb_Sheffield United,clb_Sheffield Wednesday,clb_Shimizu S-Pulse,clb_Shonan Bellmare,clb_Shrewsbury,clb_Sint-Truidense VV,clb_Sivasspor,clb_Sligo Rovers,clb_Southampton,clb_Southend United,clb_SpVgg Greuther Fürth,clb_SpVgg Unterhaching,clb_Sparta Praha,clb_Spartak Moscow,clb_Spezia,clb_Sport Club do Recife,clb_Sporting CP,clb_Sporting Kansas City,clb_Sporting Lokeren,clb_Sporting de Charleroi,clb_St. Johnstone FC,clb_St. Mirren,clb_St. Patrick's Athletic,clb_Stabæk Fotball,clb_Stade Brestois 29,clb_Stade Malherbe Caen,clb_Stade Rennais FC,clb_Stade de Reims,clb_Standard de Liège,clb_Stevenage,clb_Stoke City,clb_Strømsgodset IF,clb_Sunderland,clb_Suwon Samsung Bluewings,clb_Swansea City,clb_Swindon Town,clb_Sydney FC,clb_SønderjyskE,clb_TSG 1899 Hoffenheim,clb_TSV 1860 München,clb_TSV Hartberg,clb_Tianjin Quanjian FC,clb_Tianjin TEDA FC,clb_Tiburones Rojos de Veracruz,clb_Tigres U.A.N.L.,clb_Torino,clb_Toronto FC,clb_Tottenham Hotspur,clb_Toulouse Football Club,clb_Trabzonspor,clb_Tranmere Rovers,clb_Trelleborgs FF,clb_Tromsø IL,clb_U.N.A.M.,clb_UD Almería,clb_UD Las Palmas,clb_US Cremonese,clb_US Orléans Loiret Football,clb_US Salernitana 1919,clb_Udinese,clb_Ulsan Hyundai FC,clb_Universidad Católica,clb_Universidad de Chile,clb_Unión Española,clb_Unión La Calera,clb_Unión de Santa Fe,clb_Urawa Red Diamonds,clb_V-Varen Nagasaki,clb_VVV-Venlo,clb_Valencia CF,clb_Valenciennes FC,clb_Vancouver Whitecaps FC,clb_Vegalta Sendai,clb_Vejle Boldklub,clb_Vendsyssel FF,clb_Venezia FC,clb_VfB Stuttgart,clb_VfL Bochum 1848,clb_VfL Osnabrück,clb_VfL Sportfreunde Lotte,clb_VfL Wolfsburg,clb_VfR Aalen,clb_Viktoria Plzeň,clb_Villarreal CF,clb_Vissel Kobe,clb_Vitesse,clb_Vitória,clb_Vitória Guimarães,clb_Vitória de Setúbal,clb_Vålerenga Fotball,clb_Vélez Sarsfield,clb_Waasland-Beveren,clb_Walsall,clb_Waterford FC,clb_Watford,clb_Wellington Phoenix,clb_West Bromwich Albion,clb_West Ham United,clb_Western Sydney Wanderers,clb_Wigan Athletic,clb_Willem II,clb_Wisła Kraków,clb_Wisła Płock,clb_Wolfsberger AC,clb_Wolverhampton Wanderers,clb_Wycombe Wanderers,clb_Yeni Malatyaspor,clb_Yeovil Town,clb_Yokohama F. Marinos,clb_Zagłębie Lubin,clb_Zagłębie Sosnowiec,clb_Çaykur Rizespor,clb_Örebro SK,clb_Östersunds FK,clb_Śląsk Wrocław,pos_CAM,pos_CB,pos_CDM,pos_CF,pos_CM,pos_LAM,pos_LB,pos_LCB,pos_LCM,pos_LDM,pos_LF,pos_LM,pos_LS,pos_LW,pos_LWB,pos_RAM,pos_RB,pos_RCB,pos_RCM,pos_RDM,pos_RF,pos_RM,pos_RS,pos_RW,pos_RWB,pos_ST
0,31,94,94,110500000.0,565000.0,5.0,4.0,4.0,5.70,159.0,2.0,2.0,90.0,90.0,90.0,94.0,95.0,95.0,95.0,94.0,95.0,95.0,95.0,93.0,86.0,86.0,86.0,93.0,66.0,63.0,63.0,63.0,66.0,61.0,49.0,49.0,49.0,61.0,84.0,95.0,70.0,90.0,86.0,97.0,93.0,94.0,87.0,96.0,91.0,86.0,91.0,95.0,95.0,85.0,68.0,72.0,59.0,94.0,48.0,22.0,94.0,94.0,75.0,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,226500000.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
1,33,94,94,77000000.0,405000.0,5.0,4.0,5.0,6.20,183.0,3.0,1.0,94.0,94.0,94.0,92.0,93.0,93.0,93.0,92.0,91.0,91.0,91.0,91.0,84.0,84.0,84.0,91.0,68.0,64.0,64.0,64.0,68.0,64.0,56.0,56.0,56.0,64.0,84.0,94.0,89.0,81.0,87.0,88.0,81.0,76.0,77.0,94.0,89.0,91.0,87.0,96.0,70.0,95.0,95.0,88.0,79.0,93.0,63.0,29.0,95.0,82.0,85.0,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,127100000.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
2,26,92,93,118500000.0,290000.0,5.0,5.0,5.0,5.90,150.0,3.0,2.0,87.0,87.0,87.0,92.0,92.0,92.0,92.0,92.0,92.0,92.0,92.0,91.0,84.0,84.0,84.0,91.0,68.0,63.0,63.0,63.0,68.0,63.0,50.0,50.0,50.0,63.0,79.0,87.0,62.0,84.0,84.0,96.0,88.0,87.0,78.0,95.0,94.0,90.0,96.0,94.0,84.0,80.0,61.0,81.0,49.0,82.0,56.0,36.0,89.0,87.0,81.0,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,228100000.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
3,27,91,92,102000000.0,355000.0,4.0,5.0,4.0,5.11,154.0,3.0,3.0,85.0,85.0,85.0,90.0,90.0,90.0,90.0,90.0,91.0,91.0,91.0,91.0,90.0,90.0,90.0,91.0,80.0,80.0,80.0,80.0,80.0,76.0,69.0,69.0,69.0,76.0,93.0,82.0,55.0,92.0,82.0,86.0,85.0,83.0,91.0,91.0,78.0,76.0,79.0,91.0,77.0,91.0,63.0,90.0,75.0,91.0,76.0,61.0,87.0,94.0,79.0,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,196400000.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0

# Entranament del model

És hora de dur a terme l'entrenament del model.

En primer lloc separam la variable "Value" (la que volem preveure) de la resta del conjunt de dades per entrenar el model.

In [47]:
val = df.pop("Value")

Una vegada fet això anem a fer un split separant les dades a una raó del 75% per l'entrenament del model i un 25% per les proves damunt aquest.

In [48]:
X_train, X_test, y_train, y_test = train_test_split(df, val, test_size=0.25, random_state=42)

Una vegada ho tenim tot preparat és hora d'entrenar el nostre model.

In [49]:
reg = linear_model.LinearRegression().fit(X_train, y_train)

Anem a veure la qualitat de les nostres prediccions. Obtendrem una mètrica <a href = "https://en.wikipedia.org/wiki/Coefficient_of_determination#:~:text=In%20case%20of%20a%20single,predictor%20and%20the%20response%20variable."> $R^2$ </a>, el coeficient de la qual determina la qualitat del nostre model per preveure els resultats reals. El millor valor possible és 1, i el menor és 0.

Anem a realitzar prediccions amb les dades d'entrada que haviem separat per llavors comparar-les amb les sortides originals.

In [50]:
preds = reg.predict(X_test)
r2_score(preds, y_test)

0.9647182631687969

Com podem veure, el resultat és favorable perquè s'aproxima a 1. Es determina que existeix una correlació sustanciada entre les prediccions del nostre model i les dades reals.